$id: https://snavesutit.github.io/origins-mod-schemas/
type: object
required:
  - type
  - recipe
properties:
  type:
    description: |-
      $namespace:$fileName
      Allows a player with this power to craft the defined crafting recipe.
      $parentDescription
    markdownDescription: |-
      ### `$namespace:$fileName`
      Allows a player with this power to craft the defined crafting recipe.
      $parentDescription
    enum:
      - $namespace:$fileName
      - origins:$fileName

  recipe:
    description: The recipe to craft, including an id field which can be any arbitrary (but unique) identifier.
    $ref: ../../types/crafting_recipe.json
